apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- target:
    version: v1
    kind: ConfigMap
    name: internal-router-config
  patch: |-
    - op: replace
      path: /data/default.conf.template
      value: |
        server {
          listen 80 default_server;
          root /usr/local/app;
          access_log /dev/stdout main;
          error_log /dev/stdout;
        
          location /app-proxy {
            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            chunked_transfer_encoding off;
        
            proxy_pass http://cap-app-proxy:3017;
          }
        
          location /readyz {
            return 200 'ok';
          }
        
          location /healthz {
            return 200 'ok';
          }
        }

resources:
- github.com/codefresh-io/csdp-official/csdp/hybrid/basic/apps/internal-router?ref=0.1.14
